version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      "GitHub Actions updates":
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/SemiStep"
    schedule:
      interval: "monthly"
    groups:
      "NuGet production updates":
        dependency-type: "production"
      "NuGet development updates":
        dependency-type: "development"
