# Wait by time
10:
  ui_name: "Wait time"
  deploy_duration: longlasting
  columns:
    - key: step_duration
      default_value: "10"
      property_type_id: time
    - key: comment
      property_type_id: string

# Wait by temperature stabilization
11:
  ui_name: "Wait Temp"
  deploy_duration: immediate
  columns:
    - key: channel
      group_name: temp_sensor
      property_type_id: enum
    - key: target_value
      default_value: "0"
      property_type_id: temp
    - key: comment
      property_type_id: string

# Wait by pressure stabilization
12:
  ui_name: "Wait Pressure"
  deploy_duration: immediate
  columns:
    - key: channel
      group_name: pressure_sensor
      property_type_id: enum
    - key: target_value
      default_value: "0"
      property_type_id: pressure_bar
    - key: comment
      property_type_id: string

# Wait by pressure <=
15:
  ui_name: "Wait Pressure <="
  deploy_duration: immediate
  columns:
    - key: channel
      group_name: pressure_sensor
      property_type_id: enum
    - key: target_value
      default_value: "0"
      property_type_id: pressure_bar
    - key: comment
      property_type_id: string

# Wait by pressure >=
16:
  ui_name: "Wait Pressure >="
  deploy_duration: immediate
  columns:
    - key: channel
      group_name: pressure_sensor
      property_type_id: enum
    - key: target_value
      default_value: "0"
      property_type_id: pressure_bar
    - key: comment
      property_type_id: string

# For
20:
  ui_name: "For"
  deploy_duration: immediate
  columns:
    - key: comment
      property_type_id: string

# End_For
30:
  ui_name: "End_For"
  deploy_duration: immediate
  columns:
    - key: comment
      property_type_id: string

# Pause
40:
  ui_name: "Pause"
  deploy_duration: immediate
  columns:
    - key: comment
      property_type_id: string
